# Generated by Django 5.0.14 on 2025-06-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('company', 'Company'), ('relation', 'Relation')], max_length=50, verbose_name='relation type')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('company', models.CharField(max_length=50, verbose_name='company')),
                ('company_number', models.CharField(max_length=50, verbose_name='company number')),
                ('contact', models.CharField(max_length=50, verbose_name='particulier')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('department', 'Department')], max_length=50, verbose_name='gender')),
                ('salutation', models.CharField(max_length=50, verbose_name='salutation')),
                ('adress', models.CharField(max_length=50, verbose_name='adress')),
                ('postal', models.CharField(max_length=50, verbose_name='postal')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('post_adress', models.CharField(max_length=50, verbose_name='post adress')),
                ('post_postal', models.CharField(max_length=50, verbose_name='post postal')),
                ('post_city', models.CharField(max_length=50, verbose_name='post city')),
                ('post_country', models.CharField(max_length=50, verbose_name='post country')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('mobile', models.CharField(max_length=50, verbose_name='mobile')),
                ('mail', models.CharField(max_length=50, verbose_name='mail')),
                ('quotation_mail', models.CharField(max_length=50, verbose_name='quotation mail')),
                ('reminders_mail', models.CharField(max_length=50, verbose_name='reminders mail')),
                ('website', models.CharField(max_length=50, verbose_name='website')),
                ('iban', models.CharField(max_length=50, verbose_name='iban')),
                ('bic', models.CharField(max_length=50, verbose_name='bic')),
                ('btw', models.CharField(max_length=50, verbose_name='btw')),
                ('kind', models.CharField(max_length=50, verbose_name='kind')),
                ('general_ledger', models.CharField(max_length=50, verbose_name='general ledger')),
                ('term_of_payment', models.CharField(max_length=50, verbose_name='term of payment')),
                ('note', models.CharField(max_length=50, verbose_name='note')),
                ('newsletters', models.BooleanField(max_length=50, verbose_name='newsletters')),
            ],
            options={
                'verbose_name': 'relation',
                'verbose_name_plural': 'relations',
            },
        ),
    ]
