# Generated by Django 5.0.13 on 2025-03-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_relation_post_adress_relation_post_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='adress',
            field=models.CharField(max_length=50, verbose_name='adress'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='bic',
            field=models.CharField(max_length=50, verbose_name='bic'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='btw',
            field=models.CharField(max_length=50, verbose_name='btw'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='city',
            field=models.CharField(max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='code',
            field=models.CharField(max_length=50, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='company',
            field=models.CharField(max_length=50, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='company_number',
            field=models.CharField(max_length=50, verbose_name='company number'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='contact',
            field=models.CharField(max_length=50, verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='country',
            field=models.CharField(max_length=50, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('department', 'department')], max_length=50, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='general_ledger',
            field=models.CharField(max_length=50, verbose_name='general ledger'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='iban',
            field=models.CharField(max_length=50, verbose_name='iban'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='kind',
            field=models.CharField(max_length=50, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='mail',
            field=models.CharField(max_length=50, verbose_name='mail'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='mobile',
            field=models.CharField(max_length=50, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='newsletters',
            field=models.BooleanField(max_length=50, verbose_name='newsletters'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='note',
            field=models.CharField(max_length=50, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='post_adress',
            field=models.CharField(max_length=50, verbose_name='post adress'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='post_city',
            field=models.CharField(max_length=50, verbose_name='post city'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='post_country',
            field=models.CharField(max_length=50, verbose_name='post country'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='post_postal',
            field=models.CharField(max_length=50, verbose_name='post postal'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='postal',
            field=models.CharField(max_length=50, verbose_name='postal'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='quotation_mail',
            field=models.CharField(max_length=50, verbose_name='quotation mail'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation_type',
            field=models.CharField(choices=[('company', 'Company'), ('relation', 'Relation')], max_length=50, verbose_name='relation type'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='reminders_mail',
            field=models.CharField(max_length=50, verbose_name='reminders mail'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='salutation',
            field=models.CharField(max_length=50, verbose_name='salutation'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='term_of_payment',
            field=models.CharField(max_length=50, verbose_name='term of payment'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='website',
            field=models.CharField(max_length=50, verbose_name='website'),
        ),
    ]
