# Generated by Django 5.0.13 on 2025-03-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_alter_relation_adress_alter_relation_bic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation',
            options={'verbose_name': 'relation', 'verbose_name_plural': 'relations'},
        ),
        migrations.AlterField(
            model_name='relation',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('department', 'Department')], max_length=50, verbose_name='gender'),
        ),
    ]
