# Generated by Django 5.2.2 on 2025-06-11 21:02

import datetime
import django.db.models.deletion
import quotation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20, verbose_name='description')),
                ('colour', models.CharField(default='Green', max_length=10, verbose_name='colour')),
            ],
            options={
                'verbose_name': 'Progress',
                'verbose_name_plural': 'Progress',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20, verbose_name='description')),
                ('colour', models.CharField(default='Green', max_length=10, verbose_name='colour')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(blank=True, max_length=12, unique=True, verbose_name='quotation number')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('expiration', models.DateField(default=quotation.models.get_expiration_date, verbose_name='expiration')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='note')),
                ('progress_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.progress', verbose_name='progress')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relation.relation', verbose_name='relation')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.status', verbose_name='status')),
            ],
            options={
                'verbose_name': 'Quotation',
            },
        ),
        migrations.CreateModel(
            name='QuotationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('description', models.CharField(max_length=50, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('vat', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='VAT')),
                ('quotation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation', verbose_name='quotation rule')),
            ],
            options={
                'verbose_name': 'Quotation rule',
            },
        ),
    ]
