# Generated by Django 5.2.2 on 2025-06-23 11:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_description', models.CharField(max_length=20, verbose_name='label description')),
                ('label_colour', models.CharField(default='Green', max_length=10, verbose_name='label colour')),
            ],
            options={
                'verbose_name': 'Quotation progress',
                'verbose_name_plural': 'Quotation progress',
            },
        ),
        migrations.CreateModel(
            name='QuotationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_description', models.CharField(max_length=20, verbose_name='label description')),
                ('label_colour', models.CharField(default='Green', max_length=10, verbose_name='label colour')),
            ],
            options={
                'verbose_name': 'Quotation status',
                'verbose_name_plural': 'Quotation statuses',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, max_length=12, unique=True, verbose_name='quotation number')),
                ('quote_date', models.DateField(default=datetime.date.today, verbose_name='quotation date')),
                ('quote_expiration', models.DateField(default=datetime.datetime(2025, 7, 23, 13, 36, 59, 723205), verbose_name='quote expiration')),
                ('quote_note', models.CharField(blank=True, max_length=250, verbose_name='quotation note')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relation.relation', verbose_name='customer')),
                ('quote_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotationprogress', verbose_name='quote progress')),
                ('quote_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotationstatus', verbose_name='quote status')),
            ],
            options={
                'verbose_name': 'Quotation',
            },
        ),
        migrations.CreateModel(
            name='QuotationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_amount', models.IntegerField(verbose_name='product amount')),
                ('product_description', models.CharField(max_length=50, verbose_name='product description')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product price')),
                ('product_vat', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='product VAT')),
                ('quotation_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productitem', verbose_name='prefilled product')),
                ('quotation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation', verbose_name='quotation rule')),
            ],
            options={
                'verbose_name': 'Quotation rule',
            },
        ),
    ]
