# Generated by Django 4.2.11 on 2024-12-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20, verbose_name='description')),
                ('colour', models.CharField(default='Green', max_length=10, verbose_name='colour')),
            ],
        ),
    ]
