# Generated by Django 5.2.2 on 2025-06-23 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=50, unique=True, verbose_name='product title')),
                ('product_description', models.TextField(blank=True, verbose_name='product description')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='product price')),
                ('product_availability', models.BooleanField(default=True, verbose_name='product available')),
                ('product_created_at', models.DateTimeField(auto_now_add=True, verbose_name='product created at')),
                ('product_updated_at', models.DateTimeField(auto_now=True, verbose_name='product updated at')),
                ('product_added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='product added by')),
            ],
        ),
    ]
