# Generated by Django 5.2.2 on 2025-06-11 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermOfPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, verbose_name='description')),
                ('days', models.IntegerField(verbose_name='days')),
                ('footer', models.TextField(max_length=250, verbose_name='footer')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
            ],
            options={
                'verbose_name': 'Term of Payment',
                'verbose_name_plural': 'Terms of Payment',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('relation_type', models.CharField(choices=[('company', 'Company'), ('relation', 'Relation')], max_length=50, verbose_name='relation type')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='code')),
                ('company', models.CharField(max_length=50, verbose_name='company')),
                ('company_number', models.CharField(max_length=50, verbose_name='company number')),
                ('contact', models.CharField(max_length=50, verbose_name='contact')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('department', 'Department')], max_length=50, verbose_name='gender')),
                ('salutation', models.CharField(max_length=50, verbose_name='salutation')),
                ('adress', models.CharField(max_length=50, verbose_name='adress')),
                ('postal', models.CharField(max_length=50, verbose_name='postal')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('post_adress', models.CharField(max_length=50, verbose_name='post adress')),
                ('post_postal', models.CharField(max_length=50, verbose_name='post postal')),
                ('post_city', models.CharField(max_length=50, verbose_name='post city')),
                ('post_country', models.CharField(max_length=50, verbose_name='post country')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('mobile', models.CharField(max_length=50, verbose_name='mobile')),
                ('mail', models.CharField(max_length=50, verbose_name='mail')),
                ('quotation_mail', models.CharField(max_length=50, verbose_name='quotation mail')),
                ('reminders_mail', models.CharField(max_length=50, verbose_name='reminders mail')),
                ('website', models.CharField(max_length=50, verbose_name='website')),
                ('iban', models.CharField(max_length=50, verbose_name='iban')),
                ('bic', models.CharField(max_length=50, verbose_name='bic')),
                ('vat', models.CharField(max_length=50, verbose_name='vat')),
                ('kind', models.CharField(max_length=50, verbose_name='kind')),
                ('general_ledger', models.CharField(max_length=50, verbose_name='general ledger')),
                ('note', models.CharField(max_length=50, verbose_name='note')),
                ('newsletters', models.BooleanField(max_length=50, verbose_name='newsletters')),
                ('term_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relation.termofpayment', verbose_name='term of payment')),
            ],
            options={
                'verbose_name': 'Relation',
                'verbose_name_plural': 'Relations',
            },
        ),
    ]
