# Generated by Django 5.2.2 on 2025-06-06 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Ledger Group',
                'verbose_name_plural': 'Ledger groups',
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('category', models.CharField(choices=[('balance', 'Balance sheet'), ('profit_loss', 'Profit and loss'), ('payment', 'Payment Methods'), ('debtors', 'Debtors'), ('creditors', 'Creditors'), ('vat_current', 'VAT current account'), ('vat_other', 'VAT to be paid other'), ('vat_low', 'VAT to be paid low'), ('vat_high', 'VAT to be paid high'), ('input_tax', 'Input tax')], max_length=20, verbose_name='category')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.ledgergroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'General Ledger Account',
                'verbose_name_plural': 'General Ledger Accounts',
                'ordering': ['code'],
            },
        ),
    ]
