# Generated by Django 5.0.14 on 2025-06-06 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('category', models.CharField(choices=[('balance', 'Balance Sheet'), ('profit_loss', 'Profit and Loss'), ('payment', 'Payment Methods'), ('debtors', 'Debtors'), ('creditors', 'Creditors'), ('btw_rc', 'Btw r/c'), ('btw_overig', 'Btw af te dragen overig'), ('btw_laag', 'Btw af te dragen laag'), ('btw_hoog', 'Btw af te dragen hoog'), ('voorbelasting', 'Voorbelasting')], max_length=20, verbose_name='category')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='config.group', verbose_name='group')),
            ],
            options={
                'verbose_name': 'General Ledger Account',
                'verbose_name_plural': 'General Ledger Accounts',
                'ordering': ['code'],
            },
        ),
    ]
