# Generated by Django 5.2.2 on 2025-06-11 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField()),
                ('invoice_date', models.DateField()),
                ('description', models.CharField(max_length=20, verbose_name='description')),
                ('payment_term', models.IntegerField()),
                ('latest_payment_date', models.DateField()),
                ('invoice_text', models.CharField(max_length=20, verbose_name='invoice text')),
                ('collect_invoice_amount', models.BooleanField()),
                ('invoice_to_bookkeeping', models.BooleanField()),
                ('mutation_description', models.CharField(max_length=20, verbose_name='mutation description')),
                ('send_invoice', models.BooleanField()),
                ('relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='relation.relation')),
            ],
        ),
    ]
